server:
  port: 8090
  address: 0.0.0.0

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${ANILINK_MYSQL_URL}
    username: ${ANILINK_MYSQL_USER}
    password: ${ANILINK_MYSQL_PASS}
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    redis:
      host: ${CENTOS7_IP}
      port: 6379
      password: ${ANILINK_REDIS_PASS}
      database: 5
  rabbitmq:
    host: ${CENTOS7_IP}
    port: 5672
    virtual-host: AniLink
    username: ${ANILINK_RABBITMQ_USER}
    password: ${ANILINK_RABBITMQ_PASS}

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.video.web.main.mapper: debug

video:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    accessKey: ${MINIO_ACCESSKEY}
    secretKey: ${MINIO_SECRETKEY}

netty:
  port: 5051
